name: iceberg_pattern_example
description: The Iceberg Pattern for real-time Flutter apps with BlocSignal.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  bloc_signals: ^1.0.0
  bloc_signals_flutter: ^1.0.0
  flutter:
    sdk: flutter
  signals_core: ^7.0.0

dev_dependencies:
  bloc_signals_test: ^1.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
